version: '1.0'
services:
  # server:
  #   container_name: java
  #   image: {image_path}
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   build:
  #     context: .
  #   depends_on:
  #     - db
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
  #     - SPRING_DATASOURCE_USERNAME=compose-postgres
  #     - SPRING_DATASOURCE_PASSWORD=compose-postgres
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update - idk czy mi to potrzebne
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: {}