version: "1.1"
services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - pgdata:/var/lib/postgresql
  todo-app-server:
    container_name: todo-app-server
    image: "kryb4k/todo-app-server:latest"
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/example
      - SPRING_DATASOURCE_USERNAME=example
      - SPRING_DATASOURCE_PASSWORD=example
    depends_on:
      - db
  react_client:
    container_name: react_client
    image: "kryb4k/react-client:latest"
    ports:
      - 3000:3000
    links:
      - todo-app-server
volumes:
  pgdata: {}
